// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLZVqDRHL0iYQodV3STPZQk7kFddyVDc',
    appId: '1:551652687544:web:cc5967823656e78f9d3e4d',
    messagingSenderId: '551652687544',
    projectId: 'civicfix-81927',
    authDomain: 'civicfix-81927.firebaseapp.com',
    storageBucket: 'civicfix-81927.firebasestorage.app',
    measurementId: 'G-2GSFJCJ77D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb3YKaApgxmvCvEEfeIg472gGg8syirEw',
    appId: '1:551652687544:android:c12b368e5d82162b9d3e4d',
    messagingSenderId: '551652687544',
    projectId: 'civicfix-81927',
    storageBucket: 'civicfix-81927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDd5DFvTMNk5c44FFAW3y1v_5aU3n0l2U',
    appId: '1:551652687544:ios:643c18b1268640909d3e4d',
    messagingSenderId: '551652687544',
    projectId: 'civicfix-81927',
    storageBucket: 'civicfix-81927.firebasestorage.app',
    iosBundleId: 'com.example.civicfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDd5DFvTMNk5c44FFAW3y1v_5aU3n0l2U',
    appId: '1:551652687544:ios:643c18b1268640909d3e4d',
    messagingSenderId: '551652687544',
    projectId: 'civicfix-81927',
    storageBucket: 'civicfix-81927.firebasestorage.app',
    iosBundleId: 'com.example.civicfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxLZVqDRHL0iYQodV3STPZQk7kFddyVDc',
    appId: '1:551652687544:web:6f66cd83c9afb20f9d3e4d',
    messagingSenderId: '551652687544',
    projectId: 'civicfix-81927',
    authDomain: 'civicfix-81927.firebaseapp.com',
    storageBucket: 'civicfix-81927.firebasestorage.app',
    measurementId: 'G-37RPXHC00L',
  );
}
